name: Aquecius
description: A cooling shower for a warming globe

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  cupertino_icons: ^1.0.2
  supabase_flutter: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/shower.png
    - assets/images/fire.png
    - assets/images/time.png
    - assets/images/flag.png
    - assets/images/waterdrop.png
  fonts:
    - family: Lato
      fonts:
          - asset: fonts/Lato-Bold.ttf
            weight: 700
          - asset: fonts/Lato-Regular.ttf
            weight: 500
          - asset: fonts/Lato-Light.ttf
            weight: 300
          - asset: fonts/Lato-Thin.ttf
            weight: 200
          - asset: fonts/Lato-Italic.ttf
            style: italic
